spring:
  kafka:
    bootstrap-servers: 3.91.56.54:9093
    properties:
      security.protocol: SASL_SSL
      sasl.mechanism: SCRAM-SHA-512
      sasl.jaas.config: >
        org.apache.kafka.common.security.scram.ScramLoginModule required
        username="${KAFKA_USERNAME}"
        password="${KAFKA_PASSWORD}";
      ssl.truststore.location: classpath:truststore.p12
      ssl.truststore.password: ${TRUSTSTORE_PASSWORD}
      ssl.truststore.type: PKCS12

    consumer:
      group-id: relatorios_territorios
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
