spring:
  kafka:
    bootstrap-servers: localhost:9094
    properties:
      security.protocol: SSL

      ssl.truststore.location: C:/jw-relatorios-territorios/Back-End/relatorios_territorios/certs-localhost/client.truststore.p12
      ssl.truststore.password: changeit
      ssl.truststore.type: PKCS12

      ssl.keystore.location: C:/jw-relatorios-territorios/Back-End/relatorios_territorios/certs-localhost/client.keystore.p12
      ssl.keystore.password: changeit
      ssl.key.password: changeit
      ssl.keystore.type: PKCS12

      ssl.endpoint.identification.algorithm: ""

    consumer:
      group-id: relatorios_territorios
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
