version: '3.8'

services:
  pgadmin:
    image: dpage/pgadmin4:9.4
    container_name: pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: "pedro.alves.arruda10@gmail.com"
      PGADMIN_DEFAULT_PASSWORD: "#Pe553125237004"
    ports:
      - "5050:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin

  kafka:
    image: 'bitnami/kafka:latest'
    container_name: kafka
    restart: always
    ports:
      - '9094:9094'
    volumes:
      - ./certs-localhost:/opt/kafka/certs
    environment:
      KAFKA_CFG_NODE_ID: "0"
      KAFKA_CFG_PROCESS_ROLES: "controller,broker"
      KAFKA_CFG_LISTENERS: "SASL_SSL://0.0.0.0:9094,CONTROLLER://0.0.0.0:9093"
      KAFKA_CFG_ADVERTISED_LISTENERS: "SASL_SSL://localhost:9094"
      KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: "CONTROLLER:PLAINTEXT,SASL_SSL:SASL_SSL"
      KAFKA_CFG_CONTROLLER_QUORUM_VOTERS: "0@kafka:9093"
      KAFKA_CFG_CONTROLLER_LISTENER_NAMES: "CONTROLLER"
      KAFKA_CFG_SSL_KEYSTORE_LOCATION: "/opt/kafka/certs/broker-keystore.p12"
      KAFKA_CFG_SSL_KEYSTORE_PASSWORD: "changeit"
      KAFKA_CFG_SSL_KEY_PASSWORD: "changeit"
      KAFKA_CFG_SSL_TRUSTSTORE_LOCATION: "/opt/kafka/certs/truststore.p12"
      KAFKA_CFG_SSL_TRUSTSTORE_PASSWORD: "changeit"
      KAFKA_CFG_SASL_MECHANISM_INTER_BROKER_PROTOCOL: "SCRAM-SHA-512"
      KAFKA_CFG_SASL_ENABLED_MECHANISMS: "SCRAM-SHA-512"

volumes:
  pgadmin_data:


