version: '3.8'

services:
  pgadmin:
    image: dpage/pgadmin4:9.4
    container_name: pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: ${EMAIL_PG_ADMIN}
      PGADMIN_DEFAULT_PASSWORD: ${PASSWORD_PG_ADMIN}
    ports:
      - "5050:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin

  zookeeper:
    image: bitnami/zookeeper:latest
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    networks:
      - kafka-net

  kafka:
    image: kafka-certs-localhost
    container_name: kafka
    restart: always
    ports:
      - "9094:9094"
    depends_on:
      - zookeeper
    volumes:
      - ${LOCATION}:/bitnami/kafka/config/certs:rw
      - kafka_data:/bitnami/kafka/data
    environment:
      # Broker ID e ZooKeeper
      - KAFKA_CFG_BROKER_ID=1
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181

      # Listeners e protocolos
      - KAFKA_CFG_LISTENERS=SSL_INTERNAL://:9096,SSL_EXTERNAL://:9094
      - KAFKA_CFG_ADVERTISED_LISTENERS=SSL_INTERNAL://kafka:9096,SSL_EXTERNAL://localhost:9094
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=SSL_INTERNAL:SSL,SSL_EXTERNAL:SSL
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=SSL_INTERNAL

      # SSL
      - KAFKA_CFG_SSL_KEYSTORE_TYPE=PKCS12
      - KAFKA_CFG_SSL_KEYSTORE_LOCATION=/opt/bitnami/kafka/config/certs/kafka.server.keystore.p12
      - KAFKA_CFG_SSL_KEYSTORE_PASSWORD=changeit
      - KAFKA_CFG_SSL_KEY_PASSWORD=changeit

      - KAFKA_CFG_SSL_TRUSTSTORE_TYPE=PKCS12
      - KAFKA_CFG_SSL_TRUSTSTORE_LOCATION=/opt/bitnami/kafka/config/certs/kafka.server.truststore.p12
      - KAFKA_CFG_SSL_TRUSTSTORE_PASSWORD=changeit

      # Exige que o cliente apresente certificado
      - KAFKA_CFG_SSL_CLIENT_AUTH=required
    networks:
      - kafka-net
  kafka-2:
    image: kafka-certs-localhost
    container_name: kafka-2
    restart: always
    ports:
      - "9095:9095"
    depends_on:
      - zookeeper
    volumes:
      - ${LOCATION}:/bitnami/kafka/config/certs:rw
      - kafka_data_2:/bitnami/kafka/data
    environment:
      # Broker ID e ZooKeeper
      - KAFKA_CFG_BROKER_ID=2
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181

      # Listeners e protocolos
      - KAFKA_CFG_LISTENERS=SSL_INTERNAL://:9097,SSL_EXTERNAL://:9095
      - KAFKA_CFG_ADVERTISED_LISTENERS=SSL_INTERNAL://kafka-2:9097,SSL_EXTERNAL://localhost:9095
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=SSL_INTERNAL:SSL,SSL_EXTERNAL:SSL
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=SSL_INTERNAL

      # SSL
      - KAFKA_CFG_SSL_KEYSTORE_TYPE=PKCS12
      - KAFKA_CFG_SSL_KEYSTORE_LOCATION=/opt/bitnami/kafka/config/certs/kafka.server.keystore.p12
      - KAFKA_CFG_SSL_KEYSTORE_PASSWORD=changeit
      - KAFKA_CFG_SSL_KEY_PASSWORD=changeit

      - KAFKA_CFG_SSL_TRUSTSTORE_TYPE=PKCS12
      - KAFKA_CFG_SSL_TRUSTSTORE_LOCATION=/opt/bitnami/kafka/config/certs/kafka.server.truststore.p12
      - KAFKA_CFG_SSL_TRUSTSTORE_PASSWORD=changeit

      # Exige que o cliente apresente certificado
      - KAFKA_CFG_SSL_CLIENT_AUTH=required
    networks:
      - kafka-net

volumes:
  pgadmin_data:
  kafka_data:
  kafka_data_2:

networks:
  kafka-net:
    driver: bridge
